### ISSUE TITLE
Unable to access activity id, if I try to pass the activity through intent

### ISSUE THREAD

**Issue by sunnymopada** [GetStream/Stream-Example-Android#5]
When I try to pass Stream Activity from one android activity to another via intent, I'm unable to access activity id in the second activity due protected access it's becoming null. How can I pass it through intents.

```
Intent intent=new Intent(context,SecondActivity.class);
intent.putExtra("STREAM_ACTIVITY",activityItem);
startActivity(intent);
```

**Comment by sunnymopada** [comment]
@iandouglas @tbarbugli Can you look into this?

**Comment by dwightgunning** [comment]
Apologies this issue slipped through the cracks. This project is now quite a ways out of date and we're evaluating whether/when to resurrect it and bring it right up to date.

This is likely due to the fact the activity isn't serializable, nor does it implement Parcelable (see the various overloaded signatures on the [putExtra](https://developer.android.com/reference/android/content/Intent.html#putExtra(android.content.Intent)) method.

As we prefer to keep issues focussed on bugs and enhancements, I recommend posting further questions/clarifications to [Stack Overflow](https://stackoverflow.com/questions/tagged/getstream-io). I'll close this one out for now.
